on: [push, pull_request]
name: Push Site
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: 'Block #1'
    task:
      jobs:
      - name: Job
        commands:
          - checkout
          - docker build . -t ci
          - docker run -it -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} ci
      secrets:
        - name: api-keys
